### ISSUE TITLE
docker gateway startup error -  EOF in PeerMessage 

### ISSUE THREAD

**Issue by gregrowles** [quantnetwork/overledger-network-gateway#4]
Unable to run (developer) gateway since dashboard maintenance completed (2020-07-27); previously running gateway now gives errors:

WARNING: Error receiving message: java.io.IOException: EOF in PeerMessage constructor: type
Jul 27, 2020 7:53:13 PM network.quant.p2p.GatewayP2P buildPeers
INFO: contacted APqUqZ7_7rm2GoFc9a9CN-u6wR0iaI6WBM1RqRwByM:52.56.231.51:11337
Jul 27, 2020 7:53:14 PM peerbase.PeerConnection recvData
WARNING: Error receiving message: java.io.IOException: EOF in PeerMessage constructor: type
2020-07-27 19:53:14.250 ERROR 1 --- [ main] i.o.n.services.MeshGatewayService : Authentication failure, shutting down mesh gateway Unauthorized
Stacktrace: javax.security.sasl.AuthenticationException: Unauthorized
at network.quant.p2p.GatewayP2P.buildPeers(GatewayP2P.java:416)
at io.overledger.networkmeshgateway.services.MeshGatewayService.initialiseAndGetPeers(MeshGatewayService.java:82)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)

**Comment by gregrowles** [comment]
results in further errors:  Destroy method 'shutdown' on bean with name 'getGateway' threw an exception: java.lang.NullPointerException

... and eventually: Stopping service [Tomcat]
